name: E-commerce CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/cutie-ecommerce:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/cutie-ecommerce:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/cutie-ecommerce:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/cutie-ecommerce:buildcache,mode=max
        
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Update kube config
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        
    - name: Deploy to Kubernetes
      run: |
        $env:KUBECONFIG = "kubeconfig.yaml"
        kubectl apply -f cutie-ecommerce.yaml
        kubectl rollout restart deployment frontend-backend
        kubectl rollout restart deployment mysql
      shell: powershell